# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MetricABC": "backtest.ipynb",
         "NLLScoreline": "backtest.ipynb",
         "NLLOutcome": "backtest.ipynb",
         "Backtest": "db.ipynb",
         "EnvTyper": "cli.ipynb",
         "app": "cli.ipynb",
         "initialize_db": "cli.ipynb",
         "migrate": "cli.ipynb",
         "build_tables": "cli.ipynb",
         "ingest": "cli.ipynb",
         "resimulate": "cli.ipynb",
         "backtest": "cli.ipynb",
         "DB": "db.ipynb",
         "queries": "db.ipynb",
         "evolve_ignore": "db.ipynb",
         "prefixed_snake_case": "db.ipynb",
         "EVOLVE_IGNORE_TABLES": "db.ipynb",
         "BaseModel": "db.ipynb",
         "League": "understat.ipynb",
         "Season": "db.ipynb",
         "Matches": "db.ipynb",
         "Shots": "db.ipynb",
         "Resimulation": "db.ipynb",
         "PoiBin": "resimulation.ipynb",
         "poisson_binomial_pmf": "resimulation.ipynb",
         "resimulate_match": "resimulation.ipynb",
         "ModelABC": "team-strength.ipynb",
         "Benchmark": "team-strength.ipynb",
         "encode_parameter_key": "team-strength.ipynb",
         "decode_parameter_key": "team-strength.ipynb",
         "init_model": "team-strength.ipynb",
         "DCGoals": "team-strength.ipynb",
         "DCxG": "team-strength.ipynb",
         "DCEnsemble": "team-strength.ipynb",
         "eps_values": "team-strength.ipynb",
         "MODEL_REGISTRY": "team-strength.ipynb",
         "fetch_html": "understat.ipynb",
         "extract_json": "understat.ipynb",
         "Understat": "understat.ipynb"}

modules = ["backtest.py",
           "cli.py",
           "db.py",
           "resimulation.py",
           "team_strength.py",
           "understat.py"]

doc_url = "https://torvaney.github.io/wingback/"

git_url = "https://github.com/torvaney/wingback/tree/master/"

def custom_doc_links(name): return None
