# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/fivethirtyeight.ipynb (unless otherwise specified).

__all__ = ['fetch_data']

# Cell
import io
import csv

import requests

# Cell


def fetch_data():
    r = requests.get('https://projects.fivethirtyeight.com/soccer-api/club/spi_matches.csv')

    f = io.StringIO(r.text)
    reader = csv.reader(f, delimiter=',')

    colnames, *rows = reader

    data = [dict(zip(colnames, row)) for row in rows]

    return data