
version: 2

models:

    - name: backtest_outcome
      description: "Backtest outcome (Home/Draw/Away) probabilities"
      columns:
          - name: league_id
            tests:
                - relationships:
                    to: ref('league')
                    field: id
          - name: model
          - name: date
          - name: match_id
            tests:
                - relationships:
                    to: ref('match')
                    field: id
          - name: outcome
          - name: probability
            tests:
              - between_0_and_1
